[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
predictx_anchor = "2X5Y9i9Y4b8qbUiZiNaMc1Eh2qsarETH7bjDkhFrPuza"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/tim/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
